server:
  port: ${SERVER_PORT:8080}
  url: ${SERVER_URL:}
  x-api-key:
    header: ${X-API_KEY-HEADER:x-api-key}
    value: ${X-API-KEY:Aqswde123@}

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        jdbc:
          time_zone: UTC
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://${DATASOURCE_HOST:localhost}:${DATASOURCE_PORT:5432}/${DATASOURCE_DATABASE:commerce}?prepareThreshold=0
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:Aqswde123@}
    driverClassName: org.postgresql.Driver

  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true