server:
  port: ${SERVER_PORT:8080}

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/commerce}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:Aqswde123@}
    driverClassName: org.postgresql.Driver